"""first version

Revision ID: b4028d2c8033
Revises: 
Create Date: 2022-10-28 15:48:28.291272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4028d2c8033'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_permission',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('conf', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_auth_permission_code'), 'auth_permission', ['code'], unique=False)
    op.create_table('auth_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_role_id'), 'auth_role', ['id'], unique=False)
    op.create_index(op.f('ix_auth_role_name'), 'auth_role', ['name'], unique=True)
    op.create_table('auth_role_permission_rel',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_code', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('role_id', 'permission_code')
    )
    op.create_index(op.f('ix_auth_role_permission_rel_role_id'), 'auth_role_permission_rel', ['role_id'], unique=False)
    op.create_table('auth_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('fullname', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_user_id'), 'auth_user', ['id'], unique=False)
    op.create_index(op.f('ix_auth_user_username'), 'auth_user', ['username'], unique=True)
    op.create_table('auth_user_role_rel',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_index(op.f('ix_auth_user_role_rel_user_id'), 'auth_user_role_rel', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_user_role_rel_user_id'), table_name='auth_user_role_rel')
    op.drop_table('auth_user_role_rel')
    op.drop_index(op.f('ix_auth_user_username'), table_name='auth_user')
    op.drop_index(op.f('ix_auth_user_id'), table_name='auth_user')
    op.drop_table('auth_user')
    op.drop_index(op.f('ix_auth_role_permission_rel_role_id'), table_name='auth_role_permission_rel')
    op.drop_table('auth_role_permission_rel')
    op.drop_index(op.f('ix_auth_role_name'), table_name='auth_role')
    op.drop_index(op.f('ix_auth_role_id'), table_name='auth_role')
    op.drop_table('auth_role')
    op.drop_index(op.f('ix_auth_permission_code'), table_name='auth_permission')
    op.drop_table('auth_permission')
    # ### end Alembic commands ###
